apiVersion: v1
kind: Service
metadata:
  labels:
    name: wso2am-gateway
  name: wso2am-gateway
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    # ports that this service should serve on
    -
      name: 'pass-through-http'
      port: 8280
      targetPort: 8280
      nodePort: 32001
    -
      name: 'pass-through-https'
      port: 8243
      targetPort: 8243
      nodePort: 32002
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wso2am-gateway