apiVersion: v1
kind: Service
metadata:
  labels:
    name: wso2am-gateway-manager
  name: wso2am-gateway-manager
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    # ports that this service should serve on
    -
      name: 'pass-through-http'
      port: 8280
      targetPort: 8280
      nodePort: 32005
    -
      name: 'pass-through-https'
      port: 8243
      targetPort: 8243
      nodePort: 32006
    -
      name: 'servlet-http'
      port: 9763
      targetPort: 9763
      nodePort: 32007
    -
      name: 'servlet-https'
      port: 9443
      targetPort: 9443
      nodePort: 32008
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wso2am-gateway-manager