apiVersion: v1
kind: Service
metadata:
  labels:
    name: wso2brs-worker
  name: wso2brs-worker
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    -
      name: 'pass-through-http'
      port: 8280
      targetPort: 8280
      nodePort: 32003
    -
      name: 'pass-through-https'
      port: 8243
      targetPort: 8243
      nodePort: 32004
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wso2brs-worker
