apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2as-manager
  labels:
    name: wso2as-manager
spec:
  replicas: 1
  selector:
    name: wso2as-manager
  template:
    metadata:
      labels:
        name: wso2as-manager
    spec:
      containers:
      - name: wso2as-manager
        image: imesh/wso2as:5.2.1-v1
        env:
        -
          name: CFG_SERVER_PROFILE
          value: 'manager'
        -
          # Carbon cluster discovery parameters
          name: CONFIG_PARAM_CLUSTERING
          value: 'true'
        -
          name: CONFIG_PARAM_MEMBERSHIP_SCHEME
          value: kubernetes
        -
          name: KUBERNETES_MASTER
          value: http://172.17.8.101:8080
        -
          name: KUBERNETES_NAMESPACE
          value: default
        -
          name: KUBERNETES_SERVICES
          value: 'wso2as-manager,wso2as-worker'
        -
          # Pass-through transport ports
          name: CONFIG_PARAM_PT_HTTP_PROXY_PORT
          value: '32003'
        -
          name: CONFIG_PARAM_PT_HTTPS_PROXY_PORT
          value: '32004'
        -
          # Governance registry database
          name: CONFIG_PARAM_REGISTRY_DB_URL
          value: 'jdbc:mysql://mysql:3306/ESB_GOV_REG_DB?autoReconnect=true'
        -
          name: CONFIG_PARAM_REGISTRY_DB_USER_NAME
          value: root
        -
          name: CONFIG_PARAM_REGISTRY_DB_PASSWORD
          value: 'mysql'
        -
          # Config registry database
          name: CONFIG_PARAM_CONFIG_DB_URL
          value: 'jdbc:mysql://mysql:3306/ESB_CONF_REG_DB?autoReconnect=true'
        -
          name: CONFIG_PARAM_CONFIG_DB_USER_NAME
          value: root
        -
          name: CONFIG_PARAM_CONFIG_DB_PASSWORD
          value: 'mysql'
        -
          # User manager database
          name: CONFIG_PARAM_USER_MGT_DB_URL
          value: 'jdbc:mysql://mysql:3306/ESB_USER_DB?autoReconnect=true'
        -
          name: CONFIG_PARAM_USER_MGT_DB_USER_NAME
          value: root
        -
          name: CONFIG_PARAM_USER_MGT_DB_PASSWORD
          value: 'mysql'
        ports:
        - containerPort: 9443
